### ISSUE TITLE
Gary's comment

### ISSUE THREAD

**Issue by gary-pei** [w201rdada/portfolio-hougrammer#1]
Using machine learning (ML) for mechanical engineering design is a great idea. The beginning and ending are well written. Both are concise and to the point and should keep. I like examples in the middle. Overall it looks pretty strong. One comment might be that the scope of ML in the mechanical engineering design process needs clarification. In the example of "pushing square pegs into round holes", it seems the ML is used to solve a specific given problem at a level that design intent is specific. However, other examples show that ML is applied at even higher level such as "sleek electric car that is envy of all automotive companies". It seems to me that these involve different levels of creativity and involve different levels of engagement between designer and ML assisted toolboxes. In another words, you may ask different level 3, level 2 and level 1 questions. Do you intend to cover all?

**Comment by hougrammer** [comment]
I rewrote pretty much the whole thing according to Brooks' comments.  Hopefully, the intro and conclusion are still concise.
