### ISSUE TITLE
Nishant's helpful advice

### ISSUE THREAD

**Issue by nishanthegde** [w201rdada/portfolio-hougrammer#2]
Your idea is a non-conventional application of machine learning and very intriguing. The introduction drew me in right away. In the "middle" I would suggest adding in a few lines on what a proposed framework of implementation could look like. Perhaps something around how a model would be trained, or how it could be integrated into an existing workflow? In the "end", I would suggest adding something about the long term effects of widespread adoption of your idea.

**Comment by hougrammer** [comment]
I added some long term effects as well as more information on how the neural net would be trained.
