### ISSUE TITLE
Irene's comment

### ISSUE THREAD

**Issue by jyseo628** [w201rdada/portfolio-hougrammer#3]
I liked the idea of applying machine learning to build something collaborative in mechanical engineering, because a single engineer cannot design a space ship as you mentioned. In terms of writing, it is very clear and easy to understand even for non-engineers like myself. I liked how you gave examples of the application of data science to mechanical engineering especially.
However, I think the balance of each part seems to be a bit off from 1:2:1. While middle is very detailed and well explained, beginning and ending seem weaker. Perhaps the first paragraph of the middle part can be moved up to the beginning? I think the paragraph sounds more like a potential problem in mechanical engineering, which leads to your solution. And long term positive effects can be added more to the ending.

**Comment by hougrammer** [comment]
Moved part of the middle to the beginning as suggested.  Ratio is now closer to 1:2:1
