### ISSUE TITLE
Citekeys do not turn into citations.

### ISSUE THREAD

**Issue by hougrammer** [w201rdada/portfolio-hougrammer#4]
My website has deployed to https://w201rdada.github.io/portfolio-hougrammer/DeepCAD.html but the citekeys did not seem to turn into citations.

**Comment by brooksambrose** [comment]
Accept PR #5 and I can help debug.

**Comment by brooksambrose** [comment]
Your YAML header in `index.Rmd` is not configured for citations. See https://bookdown.org/yihui/bookdown/citations.html. Successfully completing [Step 2](https://w201rdada.github.io/syllabus/dstep2.html#dstep2) in the deployment guide will update your repo and add the necessary lines.

**Comment by hougrammer** [comment]
I appended the below to the YAML header in index.Rmd.  The citekeys have turned into citations.  Can you please just take a look and let me know that they are in the correct format ('apalike')?

bibliography: ["references.bib"]
biblio-style: "apalike"
link-citations: true
