### ISSUE TITLE
Duplicated references on build

### ISSUE THREAD

**Issue by hougrammer** [w201rdada/portfolio-hougrammer#7]
Running _build.sh creates a set of duplicate references before the final h3 header.  See https://w201rdada.github.io/portfolio-hougrammer/DeepCAD.html

**Comment by brooksambrose** [comment]
Where `split_bib: TRUE` the refs will appear at the bottom of the pages where they were used as parenthetical citations, and once for the entire project at the end of the very last page, following the behavior of `pandoc-citeproc`. Hence the `99references.Rmd` placed last to catch what you are calling the duplication.

**Comment by hougrammer** [comment]
I disabled split_bib since I only have one page.  I rebuilt and now the references only show up once.  Thanks for the help!
